### ISSUE TITLE
Does not work with attachments

### ISSUE THREAD

**Issue by stoppeye** [pagemachine/typo3-mail-css-inliner#1]
I have an extension for event registrations that sends two emails, when a user has finished the registration: one to the user and one to the event admin.
There is a method that prepares the data for both mails and then calls a generic helper method for each mail to actually send it. It's in this helper method that an instance of MailMessage is created each time an email needs to be sent:

`$mailMessage = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Mail\MailMessage::class);`

It first seemed that the mail-css-inliner plugin had no effect whatsoever, because I had always looked at the source of the user email, which gets sent first (and which is the relevant one). Only after a while I noticed that the mail-css-inliner plugin did its job well for the second mail, but not for the first one. Since the skeleton of the mail is the same for both emails (it's really only recipient, subject & mail body that are different, e.g. the <style> section is the same for both), I don't think that it's the mail itself that causes this problem. When I put some debug output into the processHtmlParts() method of the plugin, it seems that this method is only called for the second email (even though both have a text/html mime subpart).

I suspect that for some reason the postInitializeMailer signal is sent only once. Any idea what's going on here? Any suggestions on how to debug this? Many thanks!

**Comment by stoppeye** [comment]
Update: I just found out that the mail-css-inliner plugin has no effect if there is also an attachment sent with the mail. In my use case the users also get a terms&conditions pdf, which the admins obviously don't get. If I don't send that, the plugin works.
I had thought the attachment shouldn't be problematic, as it is just another mime subpart and has the encoding application/pdf, which the mail-css-inliner plugin should ignore.
But I noticed that the nesting of the mime parts is different, when there is also an attachment. I guess it could be related to that.

**Comment by mbrodala** [comment]
I can confirm that the plugin does not process the HTML parts of mails if there are attachments, I'll have a look. Thanks for reporting!

**Comment by mbrodala** [comment]
I noticed that this only affects mails where you set HTML as body. If you set anything else as body (e.g. plaintext) and add HTML as part, the plugin works as expected.

**Comment by mbrodala** [comment]
@stoppeye I've just released version 1.0.2 which should fix this issue.

**Comment by stoppeye** [comment]
Works for me now! :-)
Many thanks for this speedy bugfix.
