### ISSUE TITLE
Check for HtmlBody

### ISSUE THREAD

**Issue by msollmann** [pagemachine/typo3-mail-css-inliner#20]
With mail_css_inliner installed the sending of plaintext mails (e.g. "forgot password") leads to an error. Only html mails are converted correct and sent without errors. Could you extend the condition
`if ($message instanceof Email) {`
to
`if ($message instanceof Email && $message->getHtmlBody()) {`
in Classes/Mail/Mailer.php to only let the inliner convert an html body if we have one?

**Comment by mbrodala** [comment]
Thanks for the report! This has been fixed and released now:

https://github.com/pagemachine/typo3-mail-css-inliner/releases/tag/2.1.1

**Comment by msollmann** [comment]
Great!
