### ISSUE TITLE
Usage of TextPart in body not possible

### ISSUE THREAD

**Issue by dahaupt** [pagemachine/typo3-mail-css-inliner#24]
Example: 
https://github.com/in2code-de/femanager/blob/develop/Classes/Domain/Service/SendMailService.php#L162-L168

This case currently throws an error. Do we need to support `Symfony\Component\Mime\Part\TextPart` by adding specific handling for it? It is returned of method `getHtmlBody()` in case `$mailMessage->setBody()` is used.

I would expect `getHtmlBody()` to always return correct HTML and not an object of type `TextPart`. I also noticed that `$mailMessage->setBody()` seems to have higher priority than `$mailMessage->html()`. Probably the core should make things more strict and clear.

**Comment by mbrodala** [comment]
Can you add more details what fails exactly? Especially the exception/error with full stack trace?

**Comment by mbrodala** [comment]
Closing since there was no further feedback.
