### ISSUE TITLE
`ValueError` with TYPO3 v11.5.27

### ISSUE THREAD

**Issue by dahaupt** [pagemachine/typo3-mail-css-inliner#66]
The latest version of TYPO3 v11 includes a [bugfix](https://github.com/TYPO3/typo3/commit/bf09aeaf149118481d0b9fb67ad08fc40b832dd7) which results in this error in `\TijsVerkoyen\CssToInlineStyles\CssToInlineStyles::createDomDocumentFromHtml:116`

```php
ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty
```

It is triggered by [this method call](https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/core/Classes/Mail/FluidEmail.php#L225).

**Comment by mbrodala** [comment]
Thanks for the hint which sounds like a long standing issue in TYPO3 has been solved. We may be able to simplify our processing logic now making the current workaround (and thus this error) obsolete.

**Comment by dahaupt** [comment]
@mbrodala Thanks for your reply. I solved the issue with this patch quickly in order to be able to update TYPO3 to v11.5.27.

I guess we could use the new [BeforeMailerSentMessageEvent](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/Events/Core/Mail/BeforeMailerSentMessageEvent.html) which was introduced with TYPO3 v12.

**Comment by mbrodala** [comment]
Indeed. The `AfterMailerInitializationEvent` which was introduced as replacement for the Extbase signal back then was never a full replacement. This forced us to use the workaround.
