### ISSUE TITLE
9 LTS version

### ISSUE THREAD

**Issue by stoppeye** [pagemachine/typo3-mail-css-inliner#7]
Are you planning to release a version for T3 V9 LTS? I have your extension running on V9 in a test site. I had to make one small adjustment in ext_localconf.php. I had to remove a leading slash in the phar include ('vendors.phar/vendor/autoload.php' instead of '/vendors.phar/vendor/autoload.php').

Otherwise it seems to work fine. If I check your extension with the Upgrade / Scan Extension Files tool, everything is green. :-)

**Comment by mbrodala** [comment]
Thanks for the heads-up. The issue you mention was already fixed in master (https://github.com/pagemachine/typo3-mail-css-inliner/commit/0baf55d6991569d14f70182da27f395e10fdbfc7) so if everything is working fine for you, we can publish a new release soon.

**Comment by stoppeye** [comment]
Ok, great! Looking forward to that.

**Comment by mbrodala** [comment]
Sorry for the delay, version 2.0 has been released now which officially supports TYPO3v9.
