### ISSUE TITLE
V12 version?

### ISSUE THREAD

**Issue by stoppeye** [pagemachine/typo3-mail-css-inliner#70]
Will there be a version for T3 V12? Has anybody worked with it yet in V12?

**Comment by mbrodala** [comment]
Yes, a few first steps where taken for TYPO3v12 support or are still WIP like https://github.com/pagemachine/typo3-mail-css-inliner/pull/69

So it's a matter of finishing these for TYPO3v12 support.

**Comment by mbrodala** [comment]
Done with [version 3.1.0](https://github.com/pagemachine/typo3-mail-css-inliner/releases/tag/3.1.0) now.
