### ISSUE TITLE
Inconsistent dependency information in V3.1.0

### ISSUE THREAD

**Issue by stoppeye** [pagemachine/typo3-mail-css-inliner#76]
There is a PHP8 requirement in `composer.json` for V3.1.0. However in `ext_emconf.php` there is no dependency information for PHP.

PHP8 isn't required for TYPO3 V11 (which is still supported by your extension), which can lead to the following problem: if you update `mail_css_inliner` in a V11 installation with PHP7.4 via extension manager, you will get no dependency warning.
But after installation, you'll get an error like this:

```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in phar:///var/www/vhosts/checkin.eye-com.dev/httpdocs/t3v11/typo3conf/ext/mail_css_inliner/vendors.phar/vendor/composer/platform_check.php on line 24 
```

The BE will be completely dysfunctional and you'll have to deactivate the extension manually.

**Comment by mbrodala** [comment]
Thanks for the report. This has been fixed with [version 3.1.1](https://github.com/pagemachine/typo3-mail-css-inliner/releases/tag/3.1.1) now. PHP 8 is required for TYPO3v12 support, see https://github.com/pagemachine/typo3-mail-css-inliner/pull/74/commits/655fe58c9a55bd85802265246d78679f5a4aeab8
