### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by msollmann** [pagemachine/typo3-mail-css-inliner#9]
After installing mail_css_inliner on TYPO3 9 the whole system crashed. I guess it is the PHP version 7.3, because on a PHP-7.2-system it runs without problems.
Are you planning a PHP-7.3- or a TYPO3-10-release in the future?

**Comment by mbrodala** [comment]
Yes, a TYPO3 10 release will be published in the coming weeks. What error exactly did you get with PHP 7.3?

**Comment by msollmann** [comment]
503 Service Unavailable. 
But now I did another test on another PHP-7.3-system, where no error appeared. So the PHP version seems not to be the problem. My fault.

**Comment by mbrodala** [comment]
Thanks for checking. In any case you should check the log files of your server since the mentioned error is just a generic error.

**Comment by mbrodala** [comment]
@msollmann Version 2.1.0 is out now which supports TYPO3v10.
